name: what
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sensors_plus: ^3.0.0
  flutter_cupertino_datetime_picker: ^3.0.0 # Add this for the timer picker
  provider: 6.1.5

flutter:
  uses-material-design: true
